### ISSUE TITLE
Impossible to instal QGIS 3.12.3

### ISSUE THREAD

**Issue by bellanz80** [ptarroso/table2style#1]
Hi, 
Hello, I am trying to install, but it always returns the same error.
Both in my old profile, as in a clean profile
QGIS 3.12.3
Qindows 10 64 bit

Very thak's!

No se pudo cargar el complemento 'table2style' debido a un error al llamar a su método classFactory() 

AttributeError: type object 'QPalette' has no attribute 'PlaceholderText' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/UV/AppData/Roaming/QGIS/QGIS3\profiles\pulito/python/plugins\table2style\__init__.py", line 35, in classFactory
    return table2style(iface)
  File "C:/Users/UV/AppData/Roaming/QGIS/QGIS3\profiles\pulito/python/plugins\table2style\table2style.py", line 196, in __init__
    self.dlg = table2styleDialog(iface)
  File "C:/Users/UV/AppData/Roaming/QGIS/QGIS3\profiles\pulito/python/plugins\table2style\table2style_dialog.py", line 47, in __init__
    self.setupUi(self)
  File "", line 107, in setupUi
AttributeError: type object 'QPalette' has no attribute 'PlaceholderText'

**Comment by ptarroso** [comment]
Hi @bellanz80 

Thanks for the feedback. The problem you report is related to a known qt bug (https://bugreports.qt.io/browse/QTBUG-72555) on the version QGIS 3.12 is using. There is an easy fix. I already pushed an updated version here. I also uploaded to QGIS plugin repository version 2.1 and hope it will be available soon in QGIS plugin manager.
